package yf.user.dto;

public enum AuthResponseStatusesEnum {
    NOT_EXIST,
    NOT_AUTHORIZED,
    BLOCKED,
    WRONG_PASSWORD,
    OK,
    USER_ALREADY_EXIST,
    PASSWORDS_NOT_MATCING,
    VERIFICATION_NOT_VALID,
    PASSWORD_NOT_VALID,
    TOKEN_NOT_VALID,
    NICKNAME_WRONG,
    MIN_CHARACTER,
    NICKNAME_ALREADY_EXIST,
    SOCIAL_LOGIN_BOUNDED_TO_OTHER_USER
}
